trigger:
- none

pool:
  vmImage: ubuntu-latest

variables: 
- group: 'Azure DevOps Variables'

extends:
  template: ../base_pipeline.yaml
  parameters:
    module_name: appgateway-complete
    feed_id: '$(feed_Id)'
